Repository tututu08/FitMate, pull requests merged in 2025-06, with the labels that each got.

#152 [Feat] #145 메이트 끊기 구현
  FitMate/FitMate/Common/Components/NicknameStackView.swift
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/Main/View/MainView.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Main/ViewModel/MainViewModel.swift
  FitMate/FitMate/Scene/Mypage/View/MypageViewController.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: ✨ Feature, 노훈

#154 [Feat] #153 회원탈퇴 시, 메이트가 있으면 메이트 끊기 구현
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Main/ViewModel/MainViewModel.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: ✨ Feature, 노훈

#164 [Fix] #158 결과화면 운동 종목 및 목표 잘못 나오는 버그 픽스
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
Labels: 🐞 BugFix, 노훈

#171 [Fix] #160 모든 탭에서 운동 초대 수락 시, 운동화면으로 이동하도록 수정
  FitMate/FitMate/Scene/History/ViewModel/HistoryViewModel.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Main/ViewModel/MainViewModel.swift
  FitMate/FitMate/Scene/TabBar/TabBarController.swift
  FitMate/FitMate/Scene/TabBar/TopViewController.swift
Labels: 🐞 BugFix, 노훈

#187 [Fix]#184 메이트 끊고 메인 화면으로 이동
  FitMate/FitMate/Scene/CodeShare/View/CodeShareView.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: 🐞 BugFix, 여정

#185 [Feat] #166 로딩화면내 취소 기능 구현, 취소여부에 따른 운동 수락 분기 처리.
  FitMate/FitMate/Common/Components/Extension.swift
  FitMate/FitMate/Scene/Loading/View/LoadingView.swift
  FitMate/FitMate/Scene/Loading/View/LoadingViewController.swift
  FitMate/FitMate/Scene/Loading/ViewModel/LoadingViewModel.swift
  FitMate/FitMate/Scene/Main/View/MainView.swift
  FitMate/FitMate/Scene/TabBar/TabBarController.swift
Labels: ✨ Feature, 은서

#179 [Fix] #177 운동화면, 기록 화면 운동 수치 KM로 변환
  FitMate/FitMate/Scene/Finish/ViewModel/FinishViewModel.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/ViewModel/RunningBattleViewModel.swift
  FitMate/FitMate/Scene/Setting/View/PartnerLeftAlertView.swift
Labels: 🐞 BugFix, 노훈, 은서

#183 [FIx] #175 카카오 로그인 취소 시 모든 동작 멈추던 오류 수정
  FitMate/FitMate/Common/Service/Firebase/Auth/AuthService.swift
  FitMate/FitMate/Scene/Login/ViewModel/LoginViewModel.swift
Labels: 🐞 BugFix, 여정

#186 [Fix]#168 기록페이지 수정
  FitMate/FitMate/Scene/Finish/ViewModel/FinishViewModel.swift
  FitMate/FitMate/Scene/History/Model/HistoryModel.swift
  FitMate/FitMate/Scene/History/View/Cell/BicycleRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/CategoryCell.swift
  FitMate/FitMate/Scene/History/View/Cell/JumpRopeRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/PlankRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/RunRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/WalkRecordCell.swift
  FitMate/FitMate/Scene/History/View/HistoryView.swift
  FitMate/FitMate/Scene/History/View/HistoryViewController.swift
  FitMate/FitMate/Scene/History/ViewModel/HistoryViewModel.swift
  FitMate/FitMate/Scene/Mypage/Model/MypageModel.swift
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
  FitMate/FitMate/Scene/Mypage/View/MatepageViewController.swift
  FitMate/FitMate/Scene/Mypage/View/MypageView.swift
  FitMate/FitMate/Scene/Mypage/ViewModel/MypageViewModel.swift
Labels: 🐞 BugFix, 형윤

#191 [Fix] #182 마이데이터에 누적수치 표시되도록 수정
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
  FitMate/FitMate/Scene/Finish/ViewModel/FinishViewModel.swift
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/ViewModel/RunningBattleViewModel.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
Labels: 🐞 BugFix, 노훈

#192 [Feat] Main화면 D-day 구현
  FitMate/FitMate/Common/Components/BattleSportsView.swift
  FitMate/FitMate/Common/Components/SocialLoginButton.swift
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/KappyAlone.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/KappyAlone.imageset/KappyAlone 1.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/KappyAlone.imageset/KappyAlone 2.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/KappyAlone.imageset/KappyAlone.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/kappyWithMate.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/kappyWithMate.imageset/kappyWithMate.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/mateKappy.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/mateKappy.imageset/mateKappy.png
  FitMate/FitMate/Scene/CodeShare/ViewModel/CodeShareViewModel.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Mypage/View/MypageView.swift
Labels: ✨ Feature, 성훈

#202 [Fix] #201 줄넘기 그만하기 연동
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/ViewModel/JumpRopeBattleViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/ViewModel/JumpRopeCoopViewModel.swift
Labels: 🐞 BugFix, 노훈

#204 [Fix] #203 줄넘기 횟수, 프로그래스바 연동
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/ViewModel/JumpRopeBattleViewModel.swift
Labels: 🐞 BugFix, 노훈

#209 [Fix] #206 메이트 없을 때 메이트 끊기 시 크래시 발생 수정 / #207 줄넘기 마이페이지에 표시 안되는점 수정
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/ViewModel/JumpRopeBattleViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/ViewModel/JumpRopeCoopViewModel.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: 🐞 BugFix, 노훈

#213 [ Fix] #205 줄넘기 기록 Double -> Int 로 변경하기
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/Finish/ViewModel/FinishViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/ViewModel/JumpRopeBattleViewModel.swift
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
Labels: 🐞 BugFix, 노훈

#226 [Feat] #210 자동로그인 추가
  FitMate/FitMate/App/SceneDelegate.swift
  FitMate/FitMate/Common/Base/SplashViewController.swift
  FitMate/FitMate/Common/Service/Firebase/Auth/AuthService.swift
Labels: ✨ Feature, 형윤

#232 [Fix] #231 페이지 기록카드 색상 변경
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/ViewModel/JumpRopeCoopViewModel.swift
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
  FitMate/FitMate/Scene/Mypage/View/MatepageViewController.swift
  FitMate/FitMate/Scene/Mypage/View/MypageView.swift
  FitMate/FitMate/Scene/Mypage/View/MypageViewController.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
  FitMate/FitMate/Scene/Setting/ViewModel/SettingViewModel.swift
Labels: 🐞 BugFix, 형윤

#234 [Fix] #233 코어로케이션 업데이트 쪽에 수평 정확도 , GPS 오차 정확도 필터
  FitMate/FitMate.xcodeproj/project.pbxproj
  FitMate/FitMate/Scene/Running/RunningBattle/ViewModel/RunningBattleViewModel.swift
  FitMate/FitMate/Scene/Running/RunningCoop/ViewModel/RunningCoopViewModel.swift
Labels: 🐞 BugFix, 은서

#244 [Fix] #239 FCM 토큰 저장 위치 및 저장 시점 변경
  FitMate/FitMate/App/AppDelegate.swift
  FitMate/FitMate/Common/Service/Firebase/Auth/AuthService.swift
  FitMate/FitMate/Scene/Login/ViewModel/LoginViewModel.swift
Labels: 🐞 BugFix, 은서

#247 [Fix] #240 줄넘기 대결모드 승패 바뀌어서 저장되는 버그 픽스
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/ViewModel/JumpRopeBattleViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/ViewModel/JumpRopeCoopViewModel.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: 🐞 BugFix, 노훈

#259 [Fix]#258 마이페이지 프로필 & 설정창 UI 개선
  FitMate/FitMate/Common/Service/Firebase/GoogleService-Info.plist
  FitMate/FitMate/Scene/Mypage/View/MypageView.swift
  FitMate/FitMate/Scene/Setting/View/CustomSwitch.swift
  FitMate/FitMate/Scene/Setting/View/SettingView.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: 🐞 BugFix, 형윤

#271 [Fix] #270 마이페이지 기록카드 단위색상 개선
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
Labels: 🐞 BugFix, 형윤

#283 [Feat] #275 효과음 적용
  FitMate/FitMate/App/SceneDelegate.swift
  FitMate/FitMate/Common/Components/SoundManager.swift
  FitMate/FitMate/Resources/Sounds/fitme_invite.wav
  FitMate/FitMate/Scene/CodeShare/View/CodeShareViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
  FitMate/FitMate/Scene/Setting/ViewModel/SettingViewModel.swift
  FitMate/FitMate/Scene/TabBar/TabBarController.swift
Labels: ✨ Feature, 은서

#285 [Fix] 기록페이지 UI 디자인개선
  FitMate/FitMate/Scene/History/View/Cell/CategoryCell.swift
  FitMate/FitMate/Scene/History/View/HistoryView.swift
Labels: 🐞 BugFix, 형윤

#287 [Design] #286 FinishView 디자인 변경 및 코인 추가
  FitMate/FitMate/Resources/Assets.xcassets/image/icons/coinBackgroundNew.imageset/CoinBackGround.png
  FitMate/FitMate/Resources/Assets.xcassets/image/icons/coinBackgroundNew.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/icons/coinBackgroundNew.imageset/Group 196@2x.png
  FitMate/FitMate/Resources/Assets.xcassets/image/icons/coinBackgroundNew.imageset/Group 196@3x.png
  FitMate/FitMate/Scene/Finish/View/FinishView.swift
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
  FitMate/FitMate/Scene/Finish/ViewModel/FinishViewModel.swift
Labels: 노훈, 🎨 Design
