Repository tututu08/FitMate, pull requests merged in 2025-07, with the labels that each got.

#298 [Fix] #291 구글 계정 탈퇴 시, 세션정보 nil 에러 수정
  FitMate/FitMate/Common/Service/Firebase/Auth/AuthService.swift
Labels: 🐞 BugFix, 노훈

#299 [Fix] #292 로그인 취소 시, alert 창 안나오게 수정
  FitMate/FitMate/Scene/Login/View/LoginViewController.swift
Labels: 🐞 BugFix, 노훈

#300 [Refactor] #290 로그인뷰컨 self 참조로 인한 메모리누수 해결, 로그아웃 시 확인 알럿 추가
  FitMate/FitMate/Scene/Login/ViewModel/LoginViewModel.swift
  FitMate/FitMate/Scene/Setting/View/LogoutPopupView.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: 🛠️ Refactor, 은서

#301 [Fix] #294 UT 피드백 사항 수정(화면 깜박임, CodeShareVC 이동 방식, 운동하기 버튼 타이틀)
  FitMate/FitMate/Scene/CodeShare/View/CodeShareViewController.swift
  FitMate/FitMate/Scene/Login/View/LoginViewController.swift
  FitMate/FitMate/Scene/Login/View/NicknameViewController.swift
  FitMate/FitMate/Scene/Main/View/MainView.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
  FitMate/FitMate/Scene/TabBar/TabBarController.swift
Labels: 🐞 BugFix, 🛠️ Refactor, 노훈, 🎨 Design

#306 [Feat] #280 아바타 셀 선택하면 팝업 및 delegate proxy 충돌 오류 수정
  FitMate/FitMate.xcodeproj/project.pbxproj
  FitMate/FitMate.xcodeproj/xcshareddata/xcschemes/FitMate.xcscheme
  FitMate/FitMate/Common/Base/CustomAlertType.swift
  FitMate/FitMate/Common/Base/CustomAlertView.swift
  FitMate/FitMate/Common/Components/CustomAlertViewController.swift
  FitMate/FitMate/Scene/Shop/Model/AvatarModel.swift
  FitMate/FitMate/Scene/Shop/View/AvatarPopUpViewController.swift
  FitMate/FitMate/Scene/Shop/View/ShopView.swift
  FitMate/FitMate/Scene/Shop/View/ShopViewController.swift
  FitMate/FitMate/Scene/Shop/ViewModel/ShopViewModel.swift
Labels: 🐞 BugFix, ✨ Feature, 여정

#311 Feat/#309 운동화면에도 아바타 반영 로직 추가, 아바타 구매 시 메인 화면 아바타 연동 오류 개설
  FitMate/FitMate/Common/Components/AvatarManager.swift
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/Finish/ViewModel/FinishViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/Loading/View/LoadingViewController.swift
  FitMate/FitMate/Scene/Main/View/MainView.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
  FitMate/FitMate/Scene/Shop/View/ShopViewController.swift
Labels: 🐞 BugFix, ✨ Feature, 여정

#310 [Feat] #278 코인 UI 및 보상 로직 추가
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Scene/Finish/View/FinishView.swift
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
  FitMate/FitMate/Scene/Main/View/MainView.swift
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
Labels: ✨ Feature, 노훈, 🎨 Design

#302 [Fix] #245 줄넘기,플랭크 화면꺼짐 방지
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopViewController.swift
Labels: 성훈

#318 [Feat] #317 승/성공 시 보상받기 버튼 효과음 추가
  FitMate/FitMate/Common/Components/SoundManager.swift
  FitMate/FitMate/Resources/Sounds/coin.wav
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
Labels: ✨ Feature, 은서

#321 [Fix] #312 셀 선택시 메인 내 아바타이미지 연동 오류 수정
  FitMate/FitMate/Common/Components/AvatarManager.swift
  FitMate/FitMate/Common/Service/Firebase/Auth/AuthService.swift
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/tori.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/tori.imageset/ssido.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/tori.imageset/tori.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/toriLose.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/toriLose.imageset/ssidoLose.png
  FitMate/FitMate/Resources/Assets.xcassets/image/avatar/toriLose.imageset/toriLose.png
  FitMate/FitMate/Scene/Main/View/MainViewController.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
  FitMate/FitMate/Scene/Shop/View/ShopViewController.swift
  FitMate/FitMate/Scene/Shop/ViewModel/ShopViewModel.swift
Labels: 🐞 BugFix, 여정

#319 [Feat] #315 코인 사용 로직 상점에 적용
  FitMate/FitMate/Scene/Shop/View/ShopViewController.swift
Labels: ✨ Feature, 노훈

#320 [Fix] #295 메이트가 있는 유저에게 메이트 초대를 하면 초대 실패 Alert 띄우도록 수정
  FitMate/FitMate/Scene/CodeShare/ViewModel/MateCodeViewModel.swift
Labels: 🐞 BugFix, 노훈

#326 [Fix] #325 머지 오류 긴급수정
  FitMate/FitMate/Scene/Shop/View/ShopViewController.swift
Labels: 🐞 BugFix, 노훈

#335 [Fix] #334 마이페이지, 기록페이지 플랭크 기록 단위 및 누적기록 안보임 현상 수정
  FitMate/FitMate/Scene/History/View/Cell/PlankRecordCell.swift
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopViewController.swift
Labels: 🐞 BugFix, 형윤

#339 [Fix] #338 기록페이지 플랭크 UI 짤림현상 개선
  FitMate/FitMate/Scene/History/View/Cell/PlankRecordCell.swift
Labels: 🐞 BugFix, 형윤

#340 [Fix] #331 목표치 범위 수정, 효과음 이슈들 해결
  FitMate/FitMate/App/SceneDelegate.swift
  FitMate/FitMate/Common/Components/SoundManager.swift
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
  FitMate/FitMate/Scene/GoalSelection/ViewModel/GoalSelectionViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
Labels: 🐞 BugFix, 은서

#342 [Fix] #341 운동 선택 화면 iPhone16 Pro Max 대응
  FitMate/FitMate/Scene/SportsMode/View/SportsModeViewController.swift
Labels: 🐞 BugFix, 노훈

#344 [Fix] #343 운동모드 화면 협력모드 버튼 길이 수정
  FitMate/FitMate/Scene/SportsMode/View/SportsModeViewController.swift
Labels: 🐞 BugFix, 노훈

#345 [Fix] 상점 카테고리 오류 수정
  FitMate/FitMate/Scene/Shop/View/ShopViewController.swift
  FitMate/FitMate/Scene/Shop/ViewModel/ShopViewModel.swift
Labels: 🐞 BugFix, 여정

#359 [Fix] #352 FirestoreService 코드 정리
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
Labels: 🐞 BugFix, 노훈

#360 [Fix] #353 MatchEventService 코드 정리
  FitMate/FitMate/Common/Service/Firebase/Firestore/MatchEventService.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopViewController.swift
Labels: 🐞 BugFix, 노훈

#361 [Fix] #357 필요없는 주석 삭제 및 코드 정리
  FitMate/FitMate/Scene/CodeShare/View/CodeShareViewController.swift
  FitMate/FitMate/Scene/CodeShare/View/MateCodeViewController.swift
  FitMate/FitMate/Scene/Finish/View/FinishViewController.swift
  FitMate/FitMate/Scene/GoalSelection/View/GoalSelectionViewController.swift
  FitMate/FitMate/Scene/History/ViewModel/HistoryViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/ViewModel/JumpRopeBattleViewModel.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/ViewModel/JumpRopeCoopViewModel.swift
  FitMate/FitMate/Scene/Loading/View/LoadingViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/ViewModel/RunningBattleViewModel.swift
  FitMate/FitMate/Scene/Running/RunningCoop/ViewModel/RunningCoopViewModel.swift
  FitMate/FitMate/Scene/Setting/View/SettingViewController.swift
Labels: 🐞 BugFix, 노훈

#367 [Fix] #366 KakaoError 부분 수정
  FitMate/FitMate/Common/Base/CustomAlertView.swift
  FitMate/FitMate/Common/Components/CustomHeaderLabel.swift
  FitMate/FitMate/Common/Components/Extension.swift
  FitMate/FitMate/Common/Components/QuitAlert.swift
  FitMate/FitMate/Common/Components/SocialLoginButton.swift
  FitMate/FitMate/Common/Service/Firebase/Auth/AuthService.swift
  FitMate/FitMate/Common/Service/Firebase/Firestore/FirestoreService.swift
Labels: 🐞 BugFix, 노훈

#376 Design/#374 언어 선택 관련 UI 구현
  FitMate/FitMate/Common/Components/CustomButton.swift
  FitMate/FitMate/Common/Components/Enum.swift
  FitMate/FitMate/Resources/Assets.xcassets/image/Button/radio_selected.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/Button/radio_selected.imageset/radio_selected.png
  FitMate/FitMate/Resources/Assets.xcassets/image/Button/radio_unselected.imageset/Contents.json
  FitMate/FitMate/Resources/Assets.xcassets/image/Button/radio_unselected.imageset/radio_unselected.png
  FitMate/FitMate/Scene/History/Model/HistoryModel.swift
  FitMate/FitMate/Scene/Languages/View/LanguagesView.swift
  FitMate/FitMate/Scene/Languages/View/LanguagesViewController.swift
  FitMate/FitMate/Scene/Languages/ViewModel/LanguagesViewModel.swift
  FitMate/FitMate/Scene/Login/View/LoginView.swift
  FitMate/FitMate/Scene/Setting/View/SettingView.swift
Labels: 여정, 🎨 Design

#377 [Refactor] #373 코드 정리
  FitMate/FitMate/Scene/GoalSelection/View/GoalSelectionViewController.swift
  FitMate/FitMate/Scene/GoalSelection/ViewModel/GoalSelectionViewModel.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
  FitMate/FitMate/Scene/SportsMode/View/SportsModeViewController.swift
  FitMate/FitMate/Scene/SportsSelection/View/SportsSelectionModel.swift
  FitMate/FitMate/Scene/TabBar/TabBarController.swift
Labels: 🛠️ Refactor, 은서

#379 [Refactor] #378 매치 중복코드 struct으로 관리
  FitMate/FitMate/Common/Components/Extension.swift
  FitMate/FitMate/Common/Components/MatchInfo.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeBattle/View/JumpRopeBattleViewController.swift
  FitMate/FitMate/Scene/JumpRope/JumpRopeCoop/View/JumpRopeCoopViewController.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopViewController.swift
  FitMate/FitMate/Scene/Running/RunningBattle/View/RunningBattleViewController.swift
  FitMate/FitMate/Scene/Running/RunningCoop/View/RunningCoopViewController.swift
Labels: 🛠️ Refactor, 은서

#395 [Fix] /#394 switch 문에서 fatalError 제거 및 앱 크래시 방지
  FitMate/FitMate/Scene/History/View/HistoryViewController.swift
Labels: 🐞 BugFix, 노훈

#400 [Chore] #393 폰트 스타일 및 색상 통일화 작업
  FitMate/FitMate/Common/Base/CustomAlertView.swift
  FitMate/FitMate/Common/Base/WebViewController.swift
  FitMate/FitMate/Common/Components/BattleSportsView.swift
  FitMate/FitMate/Common/Components/CooperationSportsView.swift
  FitMate/FitMate/Common/Components/CustomAlertViewController.swift
  FitMate/FitMate/Common/Components/CustomTextField.swift
  FitMate/FitMate/Common/Components/MyRandomCodeButton.swift
  FitMate/FitMate/Common/Components/NicknameStackView.swift
  FitMate/FitMate/Common/Components/QuitAlert.swift
  FitMate/FitMate/Resources/Assets.xcassets/color/Background0.colorset/Contents.json
  FitMate/FitMate/Scene/CodeShare/View/CodeShareView.swift
  FitMate/FitMate/Scene/CodeShare/View/CodeShareViewController.swift
  FitMate/FitMate/Scene/CodeShare/View/MateCodeView.swift
  FitMate/FitMate/Scene/CodeShare/View/MateCodeViewController.swift
  FitMate/FitMate/Scene/Finish/View/FinishView.swift
  FitMate/FitMate/Scene/GoalSelection/View/GoalSelectionViewController.swift
  FitMate/FitMate/Scene/History/View/Cell/BicycleRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/CategoryCell.swift
  FitMate/FitMate/Scene/History/View/Cell/JumpRopeRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/PlankRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/RunRecordCell.swift
  FitMate/FitMate/Scene/History/View/Cell/WalkRecordCell.swift
  FitMate/FitMate/Scene/History/View/HistoryView.swift
  FitMate/FitMate/Scene/Languages/View/LanguagesView.swift
  FitMate/FitMate/Scene/Languages/View/LanguagesViewController.swift
  FitMate/FitMate/Scene/Login/View/NicknameRegisterView.swift
  FitMate/FitMate/Scene/Login/View/NicknameViewController.swift
  FitMate/FitMate/Scene/Main/View/HasNoMateViewController.swift
  FitMate/FitMate/Scene/Main/View/MainView.swift
  FitMate/FitMate/Scene/Mypage/View/Cell/WorkRecordCell.swift
  FitMate/FitMate/Scene/Mypage/View/MypageView.swift
  FitMate/FitMate/Scene/Plank/PauseAlert.swift
  FitMate/FitMate/Scene/Plank/PlankCoop/View/PlankCoopView.swift
  FitMate/FitMate/Scene/Setting/View/LogoutPopupView.swift
  FitMate/FitMate/Scene/Setting/View/MateEndPopupView.swift
  FitMate/FitMate/Scene/Setting/View/PartnerLeftAlertView.swift
  FitMate/FitMate/Scene/Setting/View/SettingView.swift
  FitMate/FitMate/Scene/Setting/View/WithdrawPopupView.swift
  FitMate/FitMate/Scene/Shop/View/Cell/ShopCategoryCell.swift
  FitMate/FitMate/Scene/Shop/View/ShopView.swift
  FitMate/FitMate/Scene/SportsMode/View/SportsModeViewController.swift
Labels: 🐞 BugFix, 노훈, 💡Chore
